### ISSUE TITLE
Overlapping chat box

### ISSUE THREAD

**Issue by gamma032steam** [mraaz/myG_RoadMap#16]
**Your Info**
gamma032

**Describe the bug**
This box needs some padding.

**Screenshots**
![image](https://user-images.githubusercontent.com/7892801/114710142-b8f69d80-9d70-11eb-931c-b842e961a6a3.png)

**To Reproduce**
Create a new account and view the sidebar.

**Comment by mraaz** [comment]
myG was initially designed for the bigger gaming screens. Smaller screens tend to have issues. I've made this a little better but its still not great.
