### ISSUE TITLE
View platform without an account

### ISSUE THREAD

**Issue by gamma032steam** [mraaz/myG_RoadMap#17]
**Your Info**
gamma032

**Is your feature request related to a problem? Please describe**
In order to promote signups, it should be possible to look around the platform without an account.

**Describe the solution you'd like**
Ability to browse profiles without making an account.

**Comment by mraaz** [comment]
@gamma032steam great idea, this is certainly on our roadmap. No timeline as of yet but we'll keep you updated.

**Comment by mraaz** [comment]
fixed!!!
