### ISSUE TITLE
Comment Profile Icon Shows Original Poster

### ISSUE THREAD

**Issue by gamma032steam** [mraaz/myG_RoadMap#18]
**Your Info**
gamma032

**Describe the bug**
The comment section of posts on the home page displays the original poster's profile picture instead of my own.

**Screenshots**
![firefox_LoHcWW05oY](https://user-images.githubusercontent.com/7892801/114712189-29062300-9d73-11eb-82e2-d0d6f769cb7b.png)

**Comment by mraaz** [comment]
resolved now :)
